/**
 * Type declarations for external modules
 */

// Convex API types - these are generated by Convex but we need stubs for development
declare module '@/convex/_generated/api' {
  // biome-ignore lint/suspicious/noExplicitAny: Convex generated types stub - overwritten when running convex dev
  type AnyFunction = any

  export const api: {
    users: {
      me: AnyFunction
      ensure: AnyFunction
      updateProfile: AnyFunction
      getByHandle: AnyFunction
      getSoulsByUser: AnyFunction
      getMySouls: AnyFunction
      getMyStarredSouls: AnyFunction
      deleteAccount: AnyFunction
    }
    souls: {
      list: AnyFunction
      getBySlug: AnyFunction
      getContent: AnyFunction
      trackDownload: AnyFunction
      toggleStar: AnyFunction
      isStarred: AnyFunction
      listFeatured: AnyFunction
      listTrending: AnyFunction
    }
    categories: {
      list: AnyFunction
    }
    search: {
      fulltext: AnyFunction
    }
  }
}

// canvas-confetti types (augment existing types)
declare module 'canvas-confetti' {
  interface Options {
    particleCount?: number
    spread?: number
    origin?: { x?: number; y?: number }
    colors?: string[]
    disableForReducedMotion?: boolean
    angle?: number
    startVelocity?: number
    decay?: number
    gravity?: number
    drift?: number
    ticks?: number
    shapes?: string[]
    scalar?: number
    zIndex?: number
  }

  function confetti(options?: Options): Promise<null>

  export = confetti
}

// Convex React hooks
declare module 'convex/react' {
  import type { FunctionReference, FunctionArgs, FunctionReturnType } from 'convex/server'
  import type { ReactNode } from 'react'

  export function useQuery<Query extends FunctionReference<'query'>>(
    query: Query,
    args?: FunctionArgs<Query>
  ): FunctionReturnType<Query> | undefined

  export function useMutation<Mutation extends FunctionReference<'mutation'>>(
    mutation: Mutation
  ): (args: FunctionArgs<Mutation>) => Promise<FunctionReturnType<Mutation>>

  export function useConvex(): unknown

  export function useConvexAuth(): {
    isLoading: boolean
    isAuthenticated: boolean
  }

  export function ConvexProvider(props: {
    client: ConvexReactClient
    children: ReactNode
  }): JSX.Element

  export class ConvexReactClient {
    constructor(url: string)
  }
}

// Convex Auth
declare module '@convex-dev/auth/react' {
  import type { ConvexReactClient } from 'convex/react'
  import type { ReactNode } from 'react'

  export function ConvexAuthProvider(props: {
    client: ConvexReactClient
    children: ReactNode
  }): JSX.Element

  export function useAuthActions(): {
    signIn: (provider: string, args?: Record<string, unknown>) => Promise<void>
    signOut: () => Promise<void>
  }

  export function Authenticated(props: { children: ReactNode }): JSX.Element | null
  export function Unauthenticated(props: { children: ReactNode }): JSX.Element | null
  export function AuthLoading(props: { children: ReactNode }): JSX.Element | null
}

// Next Plausible analytics
declare module 'next-plausible' {
  import type { ReactNode } from 'react'

  export interface PlausibleProviderProps {
    domain: string
    children: ReactNode
    trackOutboundLinks?: boolean
    trackFileDownloads?: boolean
    taggedEvents?: boolean
    hash?: boolean
    exclude?: string
    selfHosted?: boolean
    enabled?: boolean
    integrity?: string
    scriptProps?: Record<string, string>
  }

  export default function PlausibleProvider(props: PlausibleProviderProps): JSX.Element

  export function usePlausible(): (
    eventName: string,
    options?: { props?: Record<string, string | number | boolean> }
  ) => void
}
