name: "Restore Turbo cache"
description: "Restore .turbo cache (workflow must save cache after turbo run)"
runs:
  using: "composite"
  steps:
    - name: Restore Turbo cache
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ hashFiles('pnpm-lock.yaml', 'turbo.json') }}
        restore-keys: |
          ${{ runner.os }}-turbo-
